/* 页面渲染、课堂交互与测评流程。无外部依赖，可在本地服务器运行。 */
const NAV=[['home','⌂','学习概览'],['courses','▤','六周课程'],['exams','✎','测评中心'],['games','◇','思维游乐场'],['practice','✓','练习与错题'],['report','▥','成长报告'],['teacher','⚙','教师中心']];
let route='home',lessonId=0,lessonTab='learn',slide=0,playTimer=null,examTimer=null,activeExam=null,pendingBackup=null;
const main=document.getElementById('main');
const title=(name,desc,action='')=>`<div class="page-head"><div><div class="eyebrow">MATH EXPLORERS / 五年级</div><h1>${name}</h1><p>${desc}</p></div>${action}</div>`;
const button=(label,action,cls='',attrs='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const dateOf=i=>state.dates[i]||LESSONS[i].date;
const courseButton=i=>button('进入课堂 →','lesson','',`data-id="${i}"`);
function shell(){document.getElementById('nav').innerHTML=NAV.filter(x=>x[0]!=='teacher'||teacher).map(([id,icon,label])=>`<a href="#${id}" class="${route===id||route==='lesson'&&id==='courses'?'active':''}" ${route===id?'aria-current="page"':''}><span>${icon}</span>${label}</a>`).join('');document.getElementById('breadcrumb').textContent=route==='lesson'?'六周课程 / 课堂工作台':(NAV.find(x=>x[0]===route)?.[2]||'学习空间');document.getElementById('student').innerHTML=state.students.map(p=>`<option value="${esc(p.id)}" ${p.id===state.current?'selected':''}>${esc(p.name)}</option>`).join('');document.getElementById('mode').textContent=teacher?'返回学生模式':'进入教师模式'}
const heroArt=`<svg viewBox="0 0 400 240" aria-hidden="true"><ellipse cx="220" cy="207" rx="139" ry="17" fill="#cddbc7"/><path d="M83 186 L165 45 L244 186Z" fill="#e5bd73" stroke="#b78d49" stroke-width="2"/><path d="M150 193V127H219V193Z" fill="#3f8067"/><path d="M219 127L245 109V173L219 193" fill="#235f4b"/><path d="M150 127L175 109H245L219 127Z" fill="#81a890"/><circle cx="294" cy="116" r="49" fill="#fbf8e9" stroke="#809a76" stroke-width="2"/><path d="M294 67V116H343" fill="none" stroke="#d79b4f" stroke-width="3"/><text x="272" y="143" fill="#52705d" font-size="28">π</text><text x="72" y="72" fill="#476d53" font-size="21" transform="rotate(-12 72 72)">a + b</text><text x="277" y="47" fill="#698164" font-size="18">为什么？</text><circle cx="72" cy="150" r="8" fill="#bca37b"/></svg>`;
function home(){const p=pupil(),next=Math.min(p.completed.length?LESSONS.findIndex((_,i)=>!p.completed.includes(i)):0,11),n=next<0?11:next;const a=p.exams.A,b=p.exams.B;return title(`你好，${esc(p.name)}。一起发现数学的秘密。`,'从理解到表达，每一次思考都算数。',`<span class="tag">考试日 · 2026.10.24</span>`)+`<section class="hero"><div class="hero-content"><span class="eyebrow">YOUR NEXT EXPLORATION</span><h2>${p.completed.length?'继续你的数学探索':'第一站，从认识自己的起点开始'}</h2><p>${p.exams.A?'用自己的话解释，亲手验证，再独立解决一道新题。':'先完成一份20题的起点测评。不会的题可以跳过，它会帮助老师找到最适合你的学习起点。'}</p>${p.exams.A?courseButton(n):button(p.drafts.A?'继续前测 →':'开始起点测评 →','exam-open','', 'data-kind="A"')}</div><div class="hero-art">${heroArt}</div></section><div class="stats"><div class="stat"><small>课堂探索</small><strong>${p.completed.length}</strong><span>/ 12 节</span></div><div class="stat"><small>前测成绩</small><strong>${a?scoreRecord('A',a).score:'—'}</strong><span>/ 120 分</span></div><div class="stat"><small>后测成绩</small><strong>${b?scoreRecord('B',b).score:'—'}</strong><span>/ 120 分</span></div><div class="stat"><small>独立练习</small><strong>${Object.keys(p.practice).length}</strong><span>道已尝试</span></div></div><div class="grid-two"><section class="panel"><div class="section-head"><h2>接下来的探索</h2><a href="#courses">全部课程 ↗</a></div>${LESSONS.slice(n,n+3).map((l,j)=>lessonRow(n+j)).join('')}<div class="progress"><i style="width:${p.completed.length/12*100}%"></i></div><small>按自己的节奏前进 · 完成课堂后由老师标记</small></section><div><section class="panel quote"><span class="eyebrow">小老师讲堂</span><p>“如果你能把它讲明白，<br>就离真正理解更近一步。”</p><small>今天也试着问一句：为什么？</small><div class="controls">${button('准备我的讲课','talk-open','secondary',`data-id="${n}"`)}</div></section><section class="panel"><h3>一节课的学习旅程</h3><div class="process">${['听懂方法','讲给老师','游戏验证','独立做题'].map((x,i)=>`<span>${i+1} ${x}</span>`).join('')}</div></section></div></div>`}
function lessonRow(i){const l=LESSONS[i];return `<div class="lesson-row"><span class="lesson-num">${String(i+1).padStart(2,'0')}</span><div class="grow"><h3>${l.title}</h3><small>${dateOf(i)} · 120分钟 ${pupil().completed.includes(i)?'· 已完成':''}</small></div>${courseButton(i)}</div>`}
function courses(){return title('六周课程','每节课，都有一次属于你的讲台。')+`<div class="notice">10月1日、10月6日暂按正常授课；教师可在设置中调整日期。前后测占用课堂时间。</div><div class="course-grid">${LESSONS.map((l,i)=>`<article class="course"><div class="course-top"><span>第 ${String(i+1).padStart(2,'0')} 次课</span><span>${dateOf(i).slice(5).replace('-',' / ')}</span></div><div class="course-body"><span class="tag">${pupil().completed.includes(i)?'✓ 已完成':i===0||i===10?'测评课堂':'120分钟'}</span><h2 style="margin-top:14px">${l.title}</h2><p>${l.goal}</p>${courseButton(i)}</div></article>`).join('')}</div>`}
function lesson(){const l=LESSONS[lessonId];return title(l.title,`第${lessonId+1}次课 · ${dateOf(lessonId)} · ${l.goal}`,teacher?button(pupil().completed.includes(lessonId)?'取消完成标记':'标记课堂完成','complete','secondary'):'')+`<div class="tabs" role="group" aria-label="课堂环节">${[['learn','① 知识讲解'],['talk','② 小老师讲堂'],['game','③ 游戏验证'],['work','④ 独立练习'],...(teacher?[['guide','教师教案']]:[])].map(([id,label])=>button(label,'lesson-tab',lessonTab===id?'active':'',`data-tab="${id}"`)).join('')}</div><div id="lesson-body">${lessonBody()}</div>`}
function lessonBody(){const l=LESSONS[lessonId];if(lessonTab==='game')return gameView(l.game);if(lessonTab==='work')return `<section class="panel"><h2>独立练习 · 先尝试，再检查</h2><p class="muted">按题号从基础到变式练习。每次检查都会记录本次结果，错题可再次练习。</p>${l.practice.map((q,j)=>practiceQuestion(q,lessonId,j)).join('')}</section>`;if(lessonTab==='talk')return talkView();if(lessonTab==='guide')return guideView();const video=safeVideo(state.videos[lessonId]||'');return `<div class="grid-two"><section class="panel"><div class="section-head"><h2>把方法看明白</h2><span class="tag">分步讲解</span></div>${video?`<video controls preload="metadata" src="${esc(video)}"></video>`:''}<div class="lesson-stage" id="stage">${stageView()}</div><div class="controls">${button('← 上一步','slide-prev','secondary')}${button('自动播放','slide-play')}${button('下一步 →','slide-next','secondary')}<span id="slide-count" class="muted">${slide+1} / ${l.steps.length}</span></div><p class="muted" style="font-size:12px;margin-top:16px">${video?'已接入教师视频。':'本课提供分步讲解，正式视频尚未接入。教师可在教师中心添加 MP4 / WebM 视频地址。'} 自动播放每12秒切换，可随时暂停。</p></section><div><section class="panel"><h2>今天要带走的方法</h2><p>${l.goal}</p><h3>开始前，需要会</h3><p class="muted">${l.prereq}</p><h3>先试着解释</h3><p>${l.talk}</p></section><section class="panel quote"><h3>别急着看答案</h3><p style="font-size:15px">先在纸上画一画，把已知和问题写下来。</p>${button('我准备好当老师了 →','lesson-tab','secondary','data-tab="talk"')}</section></div></div>`}
function stageView(){const s=LESSONS[lessonId].steps[slide];return `<span class="eyebrow">STEP ${String(slide+1).padStart(2,'0')}</span><h2>${s[0]}</h2><p>${s[1]}</p><div class="formula">${s[2]}</div>`}
function talkView(){const p=pupil(),saved=p.talk[lessonId]||{};return `<div class="grid-two"><section class="panel"><span class="tag">现在，讲台属于你</span><h2 style="margin-top:18px">请把老师当作第一次学习的同学</h2><p>${LESSONS[lessonId].talk}</p><ol><li>用一句话介绍今天的方法。</li><li>画图或写一道例题，一步一步讲。</li><li>解释最关键的一步为什么成立。</li><li>接受追问，修正后再讲一遍。</li></ol><label for="talk-notes">我的讲课关键词（可以看自己的笔记）</label><textarea id="talk-notes" placeholder="例如：相同数量 → 相减 → 代回检查">${esc(saved.prep||'')}</textarea><div class="controls">${button('保存讲课准备','talk-save')}<span class="muted">不计入测评分数</span></div></section><section class="panel"><h2>老师可以这样问</h2><p>① 为什么这一步有效？</p><p>② 如果条件改变，怎么办？</p><p>③ 你怎样检查答案？</p>${teacher?`<label for="talk-level">本次讲解观察</label><select id="talk-level"><option value="">尚未评价</option ${saved.level==='独立讲清'?'selected':''}>独立讲清</option ${saved.level==='追问后讲清'?'selected':''}>追问后讲清</option ${saved.level==='需要重新学习'?'selected':''}>需要重新学习</option></select><p class="muted" style="margin-top:15px">这只是教学记录，不是能力标签。</p>`:'<p class="muted">允许停下来想一想，也允许重新讲一次。</p>'}</section></div>`}
function guideView(){const l=LESSONS[lessonId],flow=[0,10].includes(lessonId)?TEST_FLOW:FLOW;return `<section class="panel"><div class="section-head"><h2>第${lessonId+1}课 · 教师教案</h2>${button('打印教案','print','secondary')}</div><p><b>教学目标：</b>${l.goal}</p><p><b>前置知识：</b>${l.prereq}</p><p><b>材料：</b>白纸、笔、投屏设备；本课互动游戏与练习卷。</p><p><b>教学重点：</b>${l.steps.map(s=>s[0]).join(' → ')}</p><p><b>常见误区：</b>${l.pitfall}</p><p><b>教学处理：</b>先让学生指出条件、画图尝试，再展示例题；上台讲解出现错误时回到具体情境，修正后用新题检验。</p><div class="table-wrap"><table><thead><tr><th>环节</th><th>分钟</th><th>教师操作</th></tr></thead><tbody>${flow.map(([x,t])=>`<tr><td>${x}</td><td>${t}</td><td>${x.includes('学生')?l.talk:x.includes('游戏')?GAME_META[l.game][1]:x.includes('测评')?'先测试，不提前讲评。':x.includes('独立')?'撤掉提示，观察孩子独立使用方法。':x.includes('休息')?'离开座位，放松。':x.includes('教学')||x.includes('知识')?l.steps.map(s=>s[0]).join(' → '):'回顾、记录与调整。'}</td></tr>`).join('')}</tbody></table></div><h3 style="margin-top:20px">练习答案与讲解</h3>${l.practice.map((q,i)=>`<p>${i+1}. ${q.text}<br><b>答案：${q.answer}</b>。${q.explain}</p>`).join('')}<label for="lesson-note">课堂记录与下次调整</label><textarea id="lesson-note">${esc(pupil().notes[lessonId]||'')}</textarea><div class="controls">${button('保存课堂记录','note-save')}${button('打印学生练习卷','print-practice','secondary')}</div></section>`}
function practiceQuestion(q,i,j){const key=i+'-'+j,saved=pupil().practice[key];return `<div class="question" id="practice-${key}"><label class="qtext" for="p-${key}"><b>${j+1}.</b> ${q.text}</label>${q.svg||''}<input id="p-${key}" aria-label="第${j+1}题答案" value="${esc(saved?.answer||'')}" autocomplete="off"><button class="secondary" data-action="practice-check" data-id="${i}" data-q="${j}">检查答案</button><div class="practice-feedback" role="status">${saved?`<div class="answer ${saved.correct?'':'wrong'}">${saved.correct?'✓ 回答正确':'还需要再想一想'}${saved.correct?'。'+q.explain:''}</div>`:''}</div></div>`}
function practicePage(){const wrong=[];LESSONS.forEach((l,i)=>l.practice.forEach((q,j)=>{const s=pupil().practice[i+'-'+j];if(s&&!s.correct)wrong.push({q,i,j})}));return title('练习与错题','用一道新题，确认方法真的属于自己。')+`<section class="panel"><h2>需要再练的题 · ${wrong.length} 道</h2>${wrong.length?wrong.map(({q,i,j})=>`<p class="tag">第${i+1}课 · ${q.topic}</p>${practiceQuestion(q,i,j)}`).join(''):'<div class="empty"><strong>暂时没有待复习的错题</strong>完成课程中的独立练习后，这里会出现需要再练的题。</div>'}</section><section class="panel"><h2>选择一节课开始练习</h2>${LESSONS.map((l,i)=>`<div class="lesson-row"><span class="lesson-num">${i+1}</span><div class="grow"><h3>${l.title}</h3><small>${l.practice.length} 道课堂练习</small></div>${button('去练习','work-open','secondary',`data-id="${i}"`)}</div>`).join('')}</section>`}
function examsPage(){return title('测评中心','第二版题库 · 两套全新试卷，每卷120分。')+`<div class="notice">参照第十四届“希望杯”五年级第1试结构改编：20道填空题，每题6分。难度降低，非官方原卷。45分钟为本课程自定诊断时长。</div><div class="grid-two">${['A','B'].map(k=>{const e=pupil().exams[k],d=pupil().drafts[k];return `<section class="panel"><span class="tag">${k==='A'?'9月15日 · 起点诊断':'10月20日 · 成长复测'}</span><h2 style="margin-top:20px">${k==='A'?'前测 A 卷':'后测 B 卷'}</h2><p>20道填空题 · 每题6分 · 45分钟</p><p class="muted">独立完成，不使用计算器、AI或老师提示。题目单位已给出，请只填写答案。</p>${e?`<p class="game-number">${scoreRecord(k,e).score} <small>/ 120分</small></p><p class="muted">${new Date(e.date).toLocaleString('zh-CN')} · ${recordVersion(e)==='v1'?'第一版记录':'第二版记录'}</p>${teacher&&recordVersion(e)!==EXAM_VERSION?button('使用新版重新测评','exam-renew','secondary',`data-kind="${k}"`):''}${teacher||e.released?button('查看答题报告','exam-review','',`data-kind="${k}"`):'<p class="muted">试题讲评等待老师开放。</p>'}`:k==='B'&&!teacher&&!d?'<div class="notice">后测由老师在教师模式下启动。</div>':button(d?'继续作答':'查看考试说明','exam-open','',`data-kind="${k}"`)}${teacher?`<div class="controls">${button('打印学生卷','print-exam','secondary',`data-kind="${k}"`)}${button('教师答案','exam-key','quiet',`data-kind="${k}"`)}</div>`:''}</section>`}).join('')}</div>${historyPanel()}<section class="panel"><h2>统一规则，让进步看得清</h2><p>刷新或离开页面不会重置倒计时。答案随填写保存；截止后返回平台，会按已保存答案自动交卷。已提交的前后测不会被重复练习覆盖。</p><p class="muted">前后测知识点结构一致，但这不是经过统计等值验证的标准化测验。单次题目表现仅用于指导教学。</p></section>`}
function examIntro(k){return title(k==='A'?'前测 A 卷 · 第二版':'后测 B 卷 · 第二版','准备好了，再开始计时。')+`<section class="panel"><h2>答题说明</h2><ul><li>总分120分，20道填空题，每题6分。</li><li>45分钟，从点击开始计时起连续计算。</li><li>不会的题可以留空，先做会的题。</li><li>使用纸笔打草稿，答案填入对应位置。</li><li>不用填写单位；时间题使用“时:分”。</li><li>交卷后不能修改本次答案。</li></ul><div class="controls">${button('开始计时并答题','exam-start','',`data-kind="${k}"`)}<a href="#exams">稍后再测</a></div></section>`}
function examView(k){const d=pupil().drafts[k],questions=recordQuestions(k,d);return title(`${k==='A'?'前测':'后测'} ${k} 卷 · ${recordVersion(d)==='v1'?'第一版':'第二版'}`,'五年级数学思维测评 · 20题 / 120分')+`<div class="exam-layout"><section class="panel">${questions.map((q,i)=>`<div class="question" id="q${i}"><label class="qtext" for="e${i}"><b>${i+1}.</b> ${q.text} <small>（6分）</small></label>${q.svg}<input id="e${i}" data-exam-answer="${i}" value="${esc(d.answers[i])}" autocomplete="off" aria-label="第${i+1}题答案"></div>`).join('')}</section><aside class="panel exam-side"><small>剩余时间</small><div class="timer" id="exam-time">45:00</div><small id="answered-count"></small><div class="numbers">${questions.map((_,i)=>`<a href="#q${i}" data-scroll="q${i}" class="${d.answers[i]?'done':''}" id="num${i}">${i+1}</a>`).join('')}</div>${button('提交试卷','exam-submit')}<p class="muted" style="font-size:12px">答案自动保存在本机。离开页面，计时仍继续。</p></aside></div>`}
function examTick(){if(!activeExam||!pupil().drafts[activeExam])return;const d=pupil().drafts[activeExam],left=Math.max(0,Math.ceil((d.deadline-Date.now())/1000));const el=document.getElementById('exam-time');if(el)el.textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;const count=document.getElementById('answered-count');if(count)count.textContent=`已填写 ${d.answers.filter(x=>x.trim()).length} / 20题`;if(left===0){const k=activeExam;submitExam(k,true)}}
function submitExam(k,auto=false,confirmed=false){const d=pupil().drafts[k];if(!d)return;if(!auto&&!confirmed){document.getElementById('dialog-body').innerHTML=`<h2>确认交卷</h2><p>已填写${d.answers.filter(x=>x.trim()).length} / 20题。交卷后不能修改本次答案。</p>${button('确认提交','exam-confirm','',`data-kind="${k}"`)}`;document.getElementById('dialog').showModal();return;}if(document.getElementById('dialog').open)document.getElementById('dialog').close();pupil().exams[k]={answers:[...d.answers],version:recordVersion(d),date:new Date().toISOString(),released:false,timedOut:auto};delete pupil().drafts[k];persist();activeExam=null;clearInterval(examTimer);location.hash='exams';render();toast(auto?'时间已到，已按保存的答案自动交卷。':'试卷已提交，成绩已保存。')}
function review(k,archived=null){const e=archived||pupil().exams[k];if(!e||(!teacher&&!e.released))return examsPage();const g=scoreRecord(k,e);return title(`${k}卷答题报告 · ${recordVersion(e)==='v1'?'第一版':'第二版'}${archived?'（历史）':''}`,`${g.score} / 120分 · ${g.correct.filter(Boolean).length}题正确`)+`<section class="panel">${teacher&&!archived?button(e.released?'收起学生端讲评':'向学生开放讲评','release','secondary',`data-kind="${k}"`):''}${recordQuestions(k,e).map((q,i)=>`<div class="question"><p><b>${i+1}.</b> ${q.text}</p>${q.svg}<p>你的答案：${esc(e.answers[i]||'未作答')} <span class="tag ${g.correct[i]?'':'orange'}">${g.correct[i]?'正确 · 6分':'未答对 · 0分'}</span></p><div class="answer">答案：${q.answer}。${q.explain}</div></div>`).join('')}</section>`}
function gamesPage(){return title('思维游乐场','先预测，亲手试，再讲出背后的数学。')+`<div class="course-grid">${Object.entries(GAME_META).map(([id,[name,desc]],i)=>`<article class="course"><div class="course-top"><span>探索 ${String(i+1).padStart(2,'0')}</span><span>◇</span></div><div class="course-body"><span class="tag">${pupil().games[id]?'已探索':'待探索'}</span><h2 style="margin-top:14px">${name}</h2><p>${desc}</p>${button('进入探索 →','game-open','',`data-game-type="${id}"`)}</div></article>`).join('')}</div>`}
function report(){const p=pupil(),a=p.exams.A,b=p.exams.B,sa=a?scoreRecord('A',a).score:null,sb=b?scoreRecord('B',b).score:null;const topics=[...new Set(EXAMS.A.map(q=>q.topic))];return title('看见每一步成长','分数之外，也关注方法、解释和独立完成。',button('导出成绩表','export-report','secondary'))+`${a&&b&&recordVersion(a)!==recordVersion(b)?'<div class="notice">前后测来自不同版本，请不要直接把分差解释为学习进步。教师可保留旧记录后安排同版本测评。</div>':''}<div class="stats"><div class="stat"><small>前测 A 卷</small><strong>${sa??'—'}</strong><span>/120</span></div><div class="stat"><small>后测 B 卷</small><strong>${sb??'—'}</strong><span>/120</span></div><div class="stat"><small>分数变化</small><strong>${sa!==null&&sb!==null?(sb-sa>0?'+':'')+(sb-sa):'—'}</strong><span>分</span></div><div class="stat"><small>已记录的小老师讲课</small><strong>${Object.values(p.talk).filter(t=>t.prep||t.level).length}</strong><span>次</span></div></div>${a||b?`<section class="panel"><h2>前后测对比</h2><div class="report-bars">${[['前测',sa],['后测',sb]].map(([s,v])=>`<div class="report-bar" style="height:${v===null?0:v/120*145}px"><strong>${v??'未测'}</strong><span>${s}</span></div>`).join('')}</div></section>`:'<section class="panel empty"><strong>成长曲线，等你落下第一笔</strong>完成前测后，这里会展示真实成绩。</section>'}<section class="panel"><h2>知识点答题情况</h2><p class="muted">显示正确题数 / 对应题数。少量题目表现不等于全面掌握。</p><div class="table-wrap"><table><thead><tr><th>知识点</th><th>前测</th><th>后测</th></tr></thead><tbody>${topics.map(t=>`<tr><td>${t}</td>${['A','B'].map(k=>{const e=p.exams[k],questions=e?recordQuestions(k,e):EXAMS[k],indices=questions.map((q,i)=>q.topic===t?i:-1).filter(i=>i>=0);return `<td>${e?indices.filter(i=>isCorrect(e.answers[i],questions[i].answer)).length+' / '+indices.length:'尚未测评'}</td>`}).join('')}</tr>`).join('')}</tbody></table></div></section><section class="panel"><h2>小老师讲堂记录</h2>${Object.entries(p.talk).length?Object.entries(p.talk).map(([i,t])=>`<div class="lesson-row"><div class="grow"><h3>${LESSONS[i]?.title||'课程'}</h3><small>${esc(t.prep||'尚未填写讲解笔记')}</small></div><span class="tag">${esc(t.level||'未评价')}</span></div>`).join(''):'<p class="muted">每次课的讲解准备与教师观察会出现在这里，不计入试卷分数。</p>'}</section>`}
function teacherPage(){if(!teacher)return title('教师中心','请先切换至教师模式。');return title('教师工作台','把时间留给讲解，把记录交给系统。')+`<div class="notice">本地授课版：教师模式用于区分操作，不是密码权限隔离。请由教师保管授课设备。学生数据仅保存在当前浏览器。</div><div class="grid-two"><section class="panel"><h2>学生档案</h2><label for="new-name">添加学生姓名或昵称</label><div class="controls"><input id="new-name" maxlength="40" placeholder="例如：小禾">${button('添加学生','student-add')}</div><p class="muted">不同学生分别保存进度、测评、练习和课堂记录。</p><h3>当前学生：${esc(pupil().name)}</h3><label for="rename-name">修改昵称</label><div class="controls"><input id="rename-name" maxlength="40" value="${esc(pupil().name)}">${button('保存昵称','student-rename','secondary')}</div></section><section class="panel"><h2>备份与恢复</h2><p>更换浏览器、清理浏览器数据前，请导出备份。</p><div class="controls">${button('导出全部学习记录','backup')}${button('从备份恢复','restore','secondary')}<input type="file" id="restore-file" accept=".json,application/json" hidden></div><p class="muted">恢复会先校验文件，再要求确认替换；替换前自动下载当前数据备份。</p><h3>教学资源状态</h3><p class="muted">12节文字教案与分步讲解、36道课堂练习、40道测评题、7个互动活动已内置。正式讲解视频需要接入。</p></section></div><section class="panel"><h2>课程日期与视频资源</h2><p class="muted">视频支持可直接访问的 MP4 / WebM 地址；不支持普通视频网站页面链接。留空使用内置分步讲解。视频地址会保存到本机备份。</p><div class="table-wrap"><table><thead><tr><th>课程</th><th>授课日期</th><th>视频地址（可选）</th><th>教案</th></tr></thead><tbody>${LESSONS.map((l,i)=>`<tr><td>${i+1}. ${l.title}</td><td><input type="date" class="schedule-input" id="date-${i}" aria-label="第${i+1}课日期" value="${esc(dateOf(i))}"></td><td><input type="url" id="video-${i}" aria-label="第${i+1}课视频地址" value="${esc(state.videos[i]||'')}" placeholder="https://…/lesson.mp4"></td><td>${button('查看','guide-open','secondary',`data-id="${i}"`)}</td></tr>`).join('')}</tbody></table></div><div class="controls">${button('保存课程设置','settings-save')}</div></section>`}
function printSheet(kind,lessonIndex){const qs=kind?EXAMS[kind]:LESSONS[lessonIndex].practice;return `<div class="print-sheet"><div class="controls no-print">${button('打印 / 另存为PDF','print')}<a href="#${kind?'exams':'courses'}">返回</a></div><h1>五年级数学思维${kind?'测评 '+kind+' 卷 · 第二版':'课堂练习'}</h1><div class="sub">${kind?'20道填空题 · 每题6分 · 总分120分 · 45分钟':LESSONS[lessonIndex].title}<br>姓名：____________　日期：____________</div>${qs.map((q,i)=>`<div class="question"><p>${i+1}. ${q.text}</p>${q.svg}<p>答：________________________</p></div>`).join('')}</div>`}
function stopPlayer(){clearInterval(playTimer);playTimer=null}
function render(){stopPlayer();clearInterval(examTimer);activeExam=null;const parts=location.hash.slice(1).split('/');route=parts[0]||'home';shell();if(route==='lesson'){lessonId=Math.max(0,Math.min(11,Number(parts[1])||0));lessonTab=parts[2]||'learn';if(!['learn','talk','game','work','guide'].includes(lessonTab))lessonTab='learn';if(lessonTab==='guide'&&!teacher)lessonTab='learn';slide=0;main.innerHTML=lesson();if(lessonTab==='game')drawGame();}
 else if(route==='exam'&&['A','B'].includes(parts[1])){const k=parts[1];if(pupil().exams[k])main.innerHTML=review(k);else if(pupil().drafts[k]){activeExam=k;main.innerHTML=examView(k);examTimer=setInterval(examTick,1000);examTick()}else if(k==='B'&&!teacher)main.innerHTML=examsPage();else main.innerHTML=examIntro(k)}
 else if(route==='history'&&teacher){const h=pupil().history?.[Number(parts[1])];main.innerHTML=h?review(h.kind,h.record):examsPage()}
 else if(route==='review'&&['A','B'].includes(parts[1]))main.innerHTML=review(parts[1]);
 else if(route==='game'&&GAME_META[parts[1]]){main.innerHTML=title(GAME_META[parts[1]][0],'探索数学关系，而不只是答题。')+gameView(parts[1]);drawGame()}
 else if(route==='print'&&teacher){main.innerHTML=['A','B'].includes(parts[1])?printSheet(parts[1]):printSheet(null,Math.max(0,Math.min(11,Number(parts[1])||0)))}
 else{const pages={home,courses,exams:examsPage,games:gamesPage,practice:practicePage,report,teacher:teacherPage};main.innerHTML=(pages[route]||home)()}
 // 在任何页面检测已过期草稿，防止离开测评页面后获得额外答题时间。
 for(const k of ['A','B'])if(pupil().drafts[k]&&Date.now()>=pupil().drafts[k].deadline){submitExam(k,true);return}
 window.scrollTo(0,0);
}
function navigateLesson(i,tab='learn'){location.hash=`lesson/${i}/${tab}`;if(route==='lesson'&&lessonId===i&&lessonTab===tab)render()}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-scroll]');if(!b)return;if(b.dataset.scroll){e.preventDefault();document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'});return}if(b.dataset.game){gameAction(b.dataset.game,b);return}const action=b.dataset.action,k=b.dataset.kind,i=Number(b.dataset.id);if(!action)return;
 if(action==='lesson')navigateLesson(i);if(action==='talk-open')navigateLesson(i,'talk');if(action==='work-open')navigateLesson(i,'work');if(action==='guide-open')navigateLesson(i,'guide');if(action==='lesson-tab')navigateLesson(lessonId,b.dataset.tab);
 if(action==='complete'&&teacher){const p=pupil();p.completed=p.completed.includes(lessonId)?p.completed.filter(x=>x!==lessonId):[...p.completed,lessonId].sort((a,b)=>a-b);persist();render()}
 if(action==='slide-next'||action==='slide-prev'){stopPlayer();slide=Math.max(0,Math.min(LESSONS[lessonId].steps.length-1,slide+(action==='slide-next'?1:-1)));document.getElementById('stage').innerHTML=stageView();document.getElementById('slide-count').textContent=`${slide+1} / 3`;document.querySelector('[data-action="slide-play"]').textContent='自动播放'}
 if(action==='slide-play'){if(playTimer){stopPlayer();b.textContent='自动播放'}else{b.textContent='暂停播放';playTimer=setInterval(()=>{if(slide>=2){stopPlayer();b.textContent='重新播放';return}slide++;document.getElementById('stage').innerHTML=stageView();document.getElementById('slide-count').textContent=`${slide+1} / 3`},12000);if(slide===2){slide=0;document.getElementById('stage').innerHTML=stageView();document.getElementById('slide-count').textContent='1 / 3'}}}
 if(action==='talk-save'){pupil().talk[lessonId]={prep:document.getElementById('talk-notes').value,level:teacher?document.getElementById('talk-level').value:(pupil().talk[lessonId]?.level||'')};if(persist())toast('讲课准备已保存。')}
 if(action==='note-save'&&teacher){pupil().notes[lessonId]=document.getElementById('lesson-note').value;if(persist())toast('课堂记录已保存。')}
 if(action==='practice-check'){const j=Number(b.dataset.q),key=i+'-'+j,q=LESSONS[i].practice[j],answer=document.getElementById('p-'+key).value;if(!answer.trim())return toast('先填写你的答案。');const correct=isCorrect(answer,q.answer);pupil().practice[key]={answer,correct,attempts:(pupil().practice[key]?.attempts||0)+1,date:new Date().toISOString()};persist();document.querySelector('#practice-'+key+' .practice-feedback').innerHTML=`<div class="answer ${correct?'':'wrong'}">${correct?'✓ 正确！'+q.explain:'还没有答对。试着画图或回看方法，再做一次。'}</div>`}
 if(action==='exam-open')location.hash='exam/'+k;
 if(action==='exam-start'){if(k==='B'&&!teacher)return;if(pupil().exams[k])return;const other=['A','B'].find(x=>x!==k&&pupil().drafts[x]);if(other)return toast('请先完成正在进行的'+other+'卷。');pupil().drafts[k]={version:EXAM_VERSION,answers:Array(20).fill(''),deadline:Date.now()+45*60*1000};if(persist())render()}
 if(action==='exam-submit')submitExam(activeExam);
 if(action==='exam-confirm'){document.getElementById('dialog').close();submitExam(k,false,true);}
 if(action==='exam-renew'&&teacher){document.getElementById('dialog-body').innerHTML=`<h2>使用第二版试卷</h2><p>原${k}卷将保留在历史测评中，答案和成绩不变。确认后可开始第二版测评；此操作不立即开始计时。</p>${button('保留旧记录并启用新版','exam-renew-confirm','',`data-kind="${k}"`)}`;document.getElementById('dialog').showModal();}
 if(action==='exam-renew-confirm'&&teacher){const old=pupil().exams[k];if(old&&recordVersion(old)!==EXAM_VERSION){pupil().history??=[];pupil().history.push({kind:k,record:{...old,version:recordVersion(old)}});delete pupil().exams[k];persist()}document.getElementById('dialog').close();location.hash='exam/'+k;render()}
 if(action==='exam-review')location.hash='review/'+k;
 if(action==='release'&&teacher){pupil().exams[k].released=!pupil().exams[k].released;persist();render()}
 if(action==='print')window.print();if(action==='print-exam'&&teacher)location.hash='print/'+k;if(action==='print-practice'&&teacher)location.hash='print/'+lessonId;
 if(action==='exam-key'&&teacher){document.getElementById('dialog-body').innerHTML=`<h2>${k}卷教师答案</h2><p>每题6分，全部正确共120分。课堂讲解表现不计入测评分数。</p>${EXAMS[k].map((q,j)=>`<p><b>${j+1}. ${q.answer}</b>　${q.explain}</p>`).join('')}`;document.getElementById('dialog').showModal()}
 if(action==='game-open')location.hash='game/'+b.dataset.gameType;
 if(action==='student-add'&&teacher){const name=document.getElementById('new-name').value.trim();if(!name)return toast('请填写学生昵称。');if(state.students.length>=100)return toast('最多支持100个本机学生档案。');const p=freshStudent(name.slice(0,40));state.students.push(p);state.current=p.id;persist();render();toast('已创建独立学生档案。')}
 if(action==='student-rename'&&teacher){const n=document.getElementById('rename-name').value.trim();if(!n)return toast('昵称不能为空。');pupil().name=n.slice(0,40);persist();render()}
 if(action==='backup'&&teacher)download('思维实验室-学习备份-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(state,null,2));
 if(action==='restore'&&teacher)document.getElementById('restore-file').click();
 if(action==='restore-confirm'&&teacher&&pendingBackup){download('恢复前备份.json',JSON.stringify(state,null,2));state=pendingBackup;pendingBackup=null;document.getElementById('dialog').close();persist();render();toast('备份已恢复。')}
 if(action==='settings-save'&&teacher){const dates={},videos={};for(let j=0;j<12;j++){const d=document.getElementById('date-'+j).value,v=document.getElementById('video-'+j).value.trim();if(!d)return toast('请填写第'+(j+1)+'课日期。');if(v&&!safeVideo(v))return toast('第'+(j+1)+'课需要有效的MP4或WebM直链。');dates[j]=d;videos[j]=v}state.dates=dates;state.videos=videos;if(persist())toast('课程日期和视频设置已保存。')}
 if(action==='export-report'){const p=pupil();const csvValue=v=>'"'+String(v).replace(/^[=+@-]/,m=>"'"+m).replace(/"/g,'""')+'"';const rows=[['学生','前测/120','后测/120','完成课堂数'],[p.name,p.exams.A?scoreRecord('A',p.exams.A).score:'未测',p.exams.B?scoreRecord('B',p.exams.B).score:'未测',p.completed.length]];download('数学思维成长报告.csv','\ufeff'+rows.map(r=>r.map(csvValue).join(',')).join('\r\n'),'text/csv;charset=utf-8')}
});
document.addEventListener('input',e=>{if(e.target.hasAttribute('data-exam-answer')&&activeExam){const d=pupil().drafts[activeExam];if(Date.now()>=d.deadline){examTick();return}const i=Number(e.target.dataset.examAnswer);d.answers[i]=e.target.value.slice(0,100);persist();document.getElementById('num'+i)?.classList.toggle('done',!!d.answers[i].trim());examTick()}if(e.target.id==='cycle-n'){gameState.n=Number(e.target.value);gameState.reveal=false;document.getElementById('cycle-label').textContent=e.target.value;document.querySelectorAll('.game-item').forEach(x=>x.classList.remove('on'));document.getElementById('game-feedback').textContent=''}});
document.addEventListener('change',async e=>{if(e.target.id==='restore-file'&&teacher){const f=e.target.files[0];if(!f)return;try{if(f.size>5*1024*1024)throw Error('备份文件过大');const data=JSON.parse(await f.text());validateBackup(data);pendingBackup=data;document.getElementById('dialog-body').innerHTML=`<h2>确认恢复备份</h2><p>文件校验通过，将替换当前记录。替换前会下载现有记录备份。</p>${button('确认恢复','restore-confirm')}`;document.getElementById('dialog').showModal()}catch(err){toast('无法恢复：'+err.message)}}});
document.getElementById('student').addEventListener('change',e=>{state.current=e.target.value;persist();render()});
document.getElementById('mode').addEventListener('click',()=>{teacher=!teacher;if(!teacher&&route==='teacher')location.hash='home';render();toast(teacher?'已进入教师模式。此模式仅用于本机授课操作区分。':'已返回学生模式。')});
window.addEventListener('hashchange',render);window.addEventListener('beforeunload',()=>persist());
render();if(storageWarning)toast('未能读取旧记录，已进入临时初始状态。请检查备份后再继续。');

function historyPanel(){const list=pupil().history||[];if(!teacher||!list.length)return '';return `<section class="panel"><h2>历史测评记录</h2><p class="muted">旧卷仍按原题、原答案评分，不与新版成绩混算。</p>${list.map((h,i)=>`<div class="lesson-row"><div class="grow"><h3>${h.kind}卷 · ${recordVersion(h.record)==='v1'?'第一版':'第二版'}</h3><small>${esc(h.record.date)} · ${scoreRecord(h.kind,h.record).score}/120分</small></div><a href="#history/${i}">查看原卷与解析 →</a></div>`).join('')}</section>`}
