/* 互动任务先操作、再预测。游戏结果不进入测评成绩。 */
const GAME_META={shop:['神秘商店','比较订单，找出隐藏价格。'],cycle:['循环列车','把序号放进循环，看看它落在哪里。'],factor:['数字工厂','用整齐的分组，发现一个数的因数。'],area:['图形工坊','补回缺角，看见整体与部分。'],chase:['公交追赶','让时间前进，观察两个人的距离。'],pasture:['牧场管理','调节牛的数量，比较增长和消耗。'],allocation:['书店配货','一套有顺序的清单，胜过随意尝试。']};
let gameState={};
function gameView(type){gameState={type,step:0,found:[],start:Date.now()};return `<div class="panel"><span class="tag">互动探索 · 先想后试</span><h2 style="margin-top:14px">${GAME_META[type][0]}</h2><p class="muted">${GAME_META[type][1]}</p><div id="game-content"></div><div id="game-feedback" class="inline-feedback" role="status"></div><p class="muted">小老师追问：你看到了什么规律？改变一个条件，结果会怎样？</p></div>`}
function drawGame(){const el=document.getElementById('game-content');if(!el)return;const t=gameState.type;
 if(t==='shop')el.innerHTML=`<p>一本书和一支笔的单价分别是多少？先抵消相同的书，再求笔的单价。</p><div class="game-board"><div class="order">📗 📗 ＋ ✎ ✎ ✎ <b>＝13元</b></div><div class="order">📗 📗 ＋ ✎ ✎ ✎ ✎ ✎ <b>＝17元</b></div>${gameState.step?'<p class="game-number">多2支笔，多4元</p>':''}</div><button class="secondary" data-game="cancel">对比并抵消相同商品</button><div class="controls"><label>每支笔 <input id="game-answer" inputmode="decimal" size="5" aria-label="每支笔的价格"></label><button data-game="check" data-answer="2">验证价格</button></div>`;
 if(t==='cycle')el.innerHTML=`<p>红、黄、蓝、绿依次出现。用滑块选择序号，先预测，再显示结果。</p><div class="game-board"><div>${['红','黄','蓝','绿'].map((x,i)=>`<span class="game-item ${gameState.reveal&&((gameState.n||27)-1)%4===i?'on':''}">${x}</span>`).join('')}</div><label>序号 <input type="range" id="cycle-n" min="1" max="40" value="${gameState.n||27}"> <strong id="cycle-label">${gameState.n||27}</strong></label></div><button data-game="cycle-show">揭晓并解释</button>`;
 if(t==='factor')el.innerHTML=`<p>24份物资，每袋装几份能刚好装完？预测后尝试分组。</p><div class="game-board"><label>每袋份数 <input type="number" id="factor-n" min="1" max="24" value="${gameState.n||4}"></label><div class="controls"><button data-game="factor-show">开始分组</button></div><div id="factor-result"></div></div>`;
 if(t==='area')el.innerHTML=`<p>长8、宽6的纸，右上角剪掉边长2的正方形。剩下多少面积？</p><div class="game-board">${rect(8,6,2)}${gameState.step?'<p class="game-number">整体 8×6 − 缺角 2×2</p>':''}</div><button class="secondary" data-game="area-hint">显示补形关系</button><div class="controls"><label>剩余面积 <input id="game-answer" inputmode="numeric" size="5"></label><button data-game="check" data-answer="44">验证面积</button></div>`;
 if(t==='chase'){const s=gameState.step;el.innerHTML=`<p>小明已领先300米，两人速度分别为60、90米/分。预测几分钟追上，再逐分钟前进。</p><div class="game-board"><p>追赶开始后 <b>${s}</b> 分钟 · 距离差 ${Math.abs(300-30*s)} 米</p><svg viewBox="0 0 600 145" role="img" aria-label="两人位置随时间变化"><path d="M20 55H570 M20 110H570" stroke="#bdccbd" stroke-width="3"/><circle cx="${20+(300+60*s)/3}" cy="55" r="12" fill="#d4a75e"/><circle cx="${20+90*s/3}" cy="110" r="12" fill="#266955"/><text x="20" y="28">小明：${300+60*s}米</text><text x="20" y="90">小华：${90*s}米</text></svg></div><div class="controls"><button data-game="chase-step" ${s>=12?'disabled':''}>前进1分钟</button><button class="secondary" data-game="reset">重新观察</button></div>`;}
 if(t==='pasture'){el.innerHTML=`<p>原有草30份，每天长2份，每头牛每天吃1份。改变牛的数量，预测能吃多久。</p><div class="game-board"><label>牛的数量 <input id="cow-n" type="number" min="1" max="20" value="${gameState.n||8}"></label><div class="controls"><button data-game="pasture-show">观察净消耗</button></div><div id="pasture-result"></div></div>`;}
 if(t==='allocation')el.innerHTML=`<p>甲、乙、丙共订9本，每家2至4本。找到所有不同的方案。</p><div class="game-board"><div class="controls">${['甲','乙','丙'].map((x,i)=>`<label>${x}店 <select id="alloc-${i}"><option>2</option><option>3</option><option>4</option></select></label>`).join('')}<button data-game="allocate">收录方案</button></div><p>已找到 <b>${gameState.found.length}</b> / 7 种</p><div>${gameState.found.map(x=>`<span class="tag">${x.join(' / ')}</span>`).join(' ')}</div></div>`;
}
function gameSuccess(message){const box=document.getElementById('game-feedback');box.textContent=message;pupil().games[gameState.type]={date:new Date().toISOString()};persist()}
function gameAction(action,btn){const feedback=msg=>document.getElementById('game-feedback').textContent=msg;
 if(action==='cancel'||action==='area-hint'){gameState.step=1;drawGame()}
 if(action==='check'){const value=document.getElementById('game-answer').value;if(isCorrect(value,btn.dataset.answer))gameSuccess('验证成功！请用自己的话解释这一步为什么成立。');else feedback('还没有对上。观察两组之间的差，再试一次。')}
 if(action==='cycle-show'){gameState.n=Number(document.getElementById('cycle-n').value);gameState.reveal=true;drawGame();gameSuccess(`${gameState.n}÷4余${gameState.n%4}，对应${['红','黄','蓝','绿'][(gameState.n-1)%4]}。余数0对应最后一位。`)}
 if(action==='factor-show'){const n=Number(document.getElementById('factor-n').value);if(!Number.isInteger(n)||n<1||n>24)return feedback('请输入1到24的整数。');const r=24%n;document.getElementById('factor-result').innerHTML=`<p class="game-number">${Math.floor(24/n)}袋，剩余${r}份</p><div>${Array.from({length:Math.floor(24/n)},()=>`<span class="game-item">${n}</span>`).join('')}</div>`;if(!r)gameSuccess(`${n}是24的因数！还能找到哪些分法？`);else feedback('不能刚好分完，这个数不是24的因数。')}
 if(action==='chase-step'){gameState.step++;drawGame();if(gameState.step===10)gameSuccess('第10分钟相遇！300÷(90－60)＝10。')}
 if(action==='reset'){gameState.step=0;drawGame()}
 if(action==='pasture-show'){const n=Number(document.getElementById('cow-n').value);if(!Number.isInteger(n)||n<1||n>20)return feedback('请输入1到20的整数。');const result=n<=2?'草不会被吃完。':`能吃 ${Number((30/(n-2)).toFixed(2))} 天${30%(n-2)?'（约）':''}。`;document.getElementById('pasture-result').innerHTML=`<p class="game-number">每天净消耗 ${n-2} 份</p><p>${result}</p>`;gameSuccess('请解释：为什么要减去每天新长的2份草？')}
 if(action==='allocate'){const a=[0,1,2].map(i=>Number(document.getElementById('alloc-'+i).value));if(a.reduce((x,y)=>x+y,0)!==9)return feedback('总数不是9，请重新分配。');if(gameState.found.some(x=>x.join()===a.join()))return feedback('这个方案已经收录。换一家店的数量试试。');gameState.found.push(a);drawGame();if(gameState.found.length===7)gameSuccess('找到全部7种！现在请按甲店数量从小到大讲一遍。');else feedback('已收录。按甲店的数量分类，更不容易遗漏。')}
}
